apiVersion: v1
kind: Namespace
metadata:
  name: c2c-sk-java-gradle-qa-ns
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c2c-sk-java-gradle-qa-deployment
  namespace: c2c-sk-java-gradle-qa-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 792373136340.dkr.ecr.us-east-2.amazonaws.com/c2c:c4f7c4865e6eb052d1ababe3d6702b201f3bb72b

---
#Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: c2c-sk-java-gradle-qa-label
  name: c2c-sk-java-gradle-qa-service
  namespace: c2c-sk-java-gradle-qa-ns
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer

---